### ISSUE TITLE
name change

### ISSUE THREAD

**Issue by trebmuh** [derekdreery/jack-mixer#1]
Hi, in order to avoid a collision name with https://repo.or.cz/jack_mixer.git , could you rename this application to something else? Maybe "Novation LaunchControl XL Jack Mixer" ?

**Comment by trebmuh** [comment]
The development has resumed. See: https://rdio.space/jackmixer/ and/or https://github.com/jack-mixer/jack_mixer .

**Comment by mxmilkiib** [comment]
I'd like to package this for the AUR but there's the afore mentioned conflict. Might another name be possible? Thanks!

**Comment by richard-uk1** [comment]
Hey sorry I didn't see this until now for some reason (thanks github!). Happy to change the name, but I'm looking to move it away from relying on the LaunchControl (making midi events configurable) so I need another name.

**Comment by richard-uk1** [comment]
Maybe `mixjack` would do. Or `druid-mixer`.

**Comment by Psykopear** [comment]
john-mixer!
more seriously, I like `mixjack`, or
midi-jack-mixer
virtual-mixer

**Comment by richard-uk1** [comment]
An update on this: there are other problems with the current version of this application. I'm planning a new release with some of the SoundControl specific logic removed, in favour of configurable midi control. The midi controls will still default to the ones that I need for my SCXL, but this can be overwritten in a config file. I'm also making the number of channels and the channel names configurable (in the same config file). When I release these changes I will rename the app to "mixjack". The thing I need to make these changes is time, which I don't have so much of now but will have at some point in the future. It would also be nice if I could take advantage of the work being done on the druid reactive framework to support variable-length lists better (e.g. crochet). I think I could use the existing machinery but it would require more effort on my part.

**Comment by richard-uk1** [comment]
There is also the possibility of making the mixer more general than just jack using the new jack backend for cpal. I need to investigate if this would degrate the jack experience (in which case I wouldn't do it).

**Comment by richard-uk1** [comment]
**Update**: I've changed the name to mixjack.

I've made the mixer less dependent on my midi controller (you can now configure how it responds to midi events, along with the number and names of channels). Currently it doesn't have the eq, because it wasn't working well - I need to investigate whether working in the frequency domain is easier. I at least need to be able to visualise filters in the frequency domain. I've also currently disabled the ability to change the colors on my LaunchControl because it's not cross-platform. I might add it back in.

**Comment by trebmuh** [comment]
Thanks for the move.
I'm closing here then.
